[package]
name = "cgl"
version = "0.1.0"
authors = ["Dylan <30143500+DylanFrancis@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sdl2 = "0.34.5"
winit = "0.25.0"